### ISSUE TITLE
[SUGGESTION] Repository name is misleading

### ISSUE THREAD

**Issue by PinkDev1** [Ruben35/Icons-unFold-Rainmeter#15]
@Ruben35 
I think the name of this repo is kindof misleading, becouse new people that find this repository might think that this is the repo for the _original UnFold skin_; When this is, in fact, an expansion to said skin.

I propose we change the repo name to **"More-Icons-unFold-Rainmeter"**

**Comment by Ruben35** [comment]
Hi @PinkDev1! I think that you are rightI
In fact, i had in the past a little of trouble cause that confusion. So I think that is a good idea to change it. Thank you for your advice. 😄
